// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhls_saturation_enhance.h"

extern XHls_saturation_enhance_Config XHls_saturation_enhance_ConfigTable[];

XHls_saturation_enhance_Config *XHls_saturation_enhance_LookupConfig(u16 DeviceId) {
	XHls_saturation_enhance_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHLS_SATURATION_ENHANCE_NUM_INSTANCES; Index++) {
		if (XHls_saturation_enhance_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHls_saturation_enhance_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHls_saturation_enhance_Initialize(XHls_saturation_enhance *InstancePtr, u16 DeviceId) {
	XHls_saturation_enhance_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHls_saturation_enhance_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHls_saturation_enhance_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

