set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_XCL]
set_property IOSTANDARD LVCMOS33 [get_ports pix_clk]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_Data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_Clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adv_en]
set_property IOSTANDARD LVCMOS33 [get_ports de_i]
set_property IOSTANDARD LVCMOS33 [get_ports clr_flag]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_SKV]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_SPV]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_XLE]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_XSTL]
set_property IOSTANDARD LVCMOS33 [get_ports hs_i]
set_property IOSTANDARD LVCMOS33 [get_ports pwr_com]
set_property IOSTANDARD LVCMOS33 [get_ports pwr_good]
set_property IOSTANDARD LVCMOS33 [get_ports pwr_up]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports vs_i]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports wake_up]
set_property PACKAGE_PIN N18 [get_ports clk]
set_property PACKAGE_PIN P16 [get_ports rst_n]
set_property PACKAGE_PIN Y14 [get_ports EPD_XCL]
set_property PACKAGE_PIN M20 [get_ports adv_en]
set_property PACKAGE_PIN T12 [get_ports clr_flag]
set_property PACKAGE_PIN Y19 [get_ports sda]
set_property PACKAGE_PIN Y17 [get_ports scl]
set_property PACKAGE_PIN W18 [get_ports wake_up]
set_property PACKAGE_PIN C20 [get_ports de_i]
set_property PACKAGE_PIN W14 [get_ports {EPD_DOUT[0]}]
set_property PACKAGE_PIN W16 [get_ports {EPD_DOUT[1]}]
set_property PACKAGE_PIN V16 [get_ports {EPD_DOUT[2]}]
set_property PACKAGE_PIN R18 [get_ports {EPD_DOUT[3]}]
set_property PACKAGE_PIN T17 [get_ports {EPD_DOUT[4]}]
set_property PACKAGE_PIN W13 [get_ports {EPD_DOUT[5]}]
set_property PACKAGE_PIN V12 [get_ports {EPD_DOUT[6]}]
set_property PACKAGE_PIN T15 [get_ports {EPD_DOUT[7]}]
set_property PACKAGE_PIN V18 [get_ports EPD_SKV]
set_property PACKAGE_PIN V17 [get_ports EPD_SPV]
set_property PACKAGE_PIN V13 [get_ports EPD_XLE]
set_property PACKAGE_PIN U15 [get_ports EPD_XSTL]
set_property PACKAGE_PIN F20 [get_ports hs_i]
set_property PACKAGE_PIN H17 [get_ports pix_clk]
set_property PACKAGE_PIN W19 [get_ports pwr_com]
set_property PACKAGE_PIN Y16 [get_ports pwr_good]
set_property PACKAGE_PIN Y18 [get_ports pwr_up]
set_property PACKAGE_PIN F19 [get_ports {rgb_i[0]}]
set_property PACKAGE_PIN L20 [get_ports {rgb_i[1]}]
set_property PACKAGE_PIN L19 [get_ports {rgb_i[2]}]
set_property PACKAGE_PIN G18 [get_ports {rgb_i[3]}]
set_property PACKAGE_PIN B20 [get_ports {rgb_i[4]}]
set_property PACKAGE_PIN K16 [get_ports {rgb_i[5]}]
set_property PACKAGE_PIN J18 [get_ports {rgb_i[6]}]
set_property PACKAGE_PIN J16 [get_ports {rgb_i[7]}]
set_property PACKAGE_PIN H18 [get_ports {rgb_i[8]}]
set_property PACKAGE_PIN G19 [get_ports {rgb_i[9]}]
set_property PACKAGE_PIN G20 [get_ports {rgb_i[10]}]
set_property PACKAGE_PIN H16 [get_ports {rgb_i[11]}]
set_property PACKAGE_PIN E17 [get_ports {rgb_i[12]}]
set_property PACKAGE_PIN D19 [get_ports {rgb_i[13]}]
set_property PACKAGE_PIN D18 [get_ports {rgb_i[14]}]
set_property PACKAGE_PIN D20 [get_ports {rgb_i[15]}]
set_property PACKAGE_PIN B19 [get_ports {rgb_i[16]}]
set_property PACKAGE_PIN A20 [get_ports {rgb_i[17]}]
set_property PACKAGE_PIN E18 [get_ports {rgb_i[18]}]
set_property PACKAGE_PIN E19 [get_ports {rgb_i[19]}]
set_property PACKAGE_PIN F16 [get_ports {rgb_i[20]}]
set_property PACKAGE_PIN F17 [get_ports {rgb_i[21]}]
set_property PACKAGE_PIN H15 [get_ports {rgb_i[22]}]
set_property PACKAGE_PIN G15 [get_ports {rgb_i[23]}]
set_property PACKAGE_PIN G17 [get_ports vs_i]
set_property PACKAGE_PIN U18 [get_ports TMDS_Clk_p]
set_property PACKAGE_PIN V20 [get_ports {TMDS_Data_p[0]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_Data_p[1]}]
set_property PACKAGE_PIN N20 [get_ports {TMDS_Data_p[2]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pix_clk_IBUF]

create_clock -period 20.000 -name clk [get_ports clk]
create_clock -period 10000.000 -name scl [get_ports scl]
create_clock -period 6.734 -name pix_clk [get_ports pix_clk]
create_clock -period 33.333 -name EPD_XCL [get_ports EPD_XCL]

set_input_delay -clock [get_clocks pix_clk] -rise -min 2.000 [get_ports {de_i hs_i {rgb_i[0]} {rgb_i[1]} {rgb_i[2]} {rgb_i[3]} {rgb_i[4]} {rgb_i[5]} {rgb_i[6]} {rgb_i[7]} {rgb_i[8]} {rgb_i[9]} {rgb_i[10]} {rgb_i[11]} {rgb_i[12]} {rgb_i[13]} {rgb_i[14]} {rgb_i[15]} {rgb_i[16]} {rgb_i[17]} {rgb_i[18]} {rgb_i[19]} {rgb_i[20]} {rgb_i[21]} {rgb_i[22]} {rgb_i[23]} vs_i}]

set_input_delay -clock [get_clocks pix_clk] -rise -max 4.700 [get_ports {de_i hs_i {rgb_i[0]} {rgb_i[1]} {rgb_i[2]} {rgb_i[3]} {rgb_i[4]} {rgb_i[5]} {rgb_i[6]} {rgb_i[7]} {rgb_i[8]} {rgb_i[9]} {rgb_i[10]} {rgb_i[11]} {rgb_i[12]} {rgb_i[13]} {rgb_i[14]} {rgb_i[15]} {rgb_i[16]} {rgb_i[17]} {rgb_i[18]} {rgb_i[19]} {rgb_i[20]} {rgb_i[21]} {rgb_i[22]} {rgb_i[23]} vs_i}]

set_false_path -from [get_ports rst_n] -to [all_registers]




