set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clr_flag]

set_property IOSTANDARD LVCMOS33 [get_ports k2]
set_property IOSTANDARD LVCMOS33 [get_ports k3]

set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports scl]

set_property IOSTANDARD LVCMOS33 [get_ports epd_pwr_sw]
set_property IOSTANDARD LVCMOS33 [get_ports epd_pwr_en]
set_property IOSTANDARD LVCMOS33 [get_ports pwr_good]

set_property IOSTANDARD LVCMOS33 [get_ports EPD_SKV]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_SPV]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_XCL]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_XLE]
set_property IOSTANDARD LVCMOS33 [get_ports EPD_XSTL]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EPD_DOUT[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports pix_clk]
set_property IOSTANDARD LVCMOS33 [get_ports de_i]
set_property IOSTANDARD LVCMOS33 [get_ports hs_i]
set_property IOSTANDARD LVCMOS33 [get_ports vs_i]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gray_i[0]}]


set_property PACKAGE_PIN N18 [get_ports clk]
set_property PACKAGE_PIN L20 [get_ports rst_n]
set_property PACKAGE_PIN M20 [get_ports clr_flag]

set_property PACKAGE_PIN L17 [get_ports k2]
set_property PACKAGE_PIN M18 [get_ports k3]

set_property PACKAGE_PIN N20 [get_ports sda]
set_property PACKAGE_PIN M19 [get_ports scl]

set_property PACKAGE_PIN L19 [get_ports epd_pwr_sw]
set_property PACKAGE_PIN L16 [get_ports epd_pwr_en]
set_property PACKAGE_PIN K19 [get_ports pwr_good]

set_property PACKAGE_PIN A20 [get_ports EPD_SKV]
set_property PACKAGE_PIN H16 [get_ports EPD_SPV]
set_property PACKAGE_PIN B19 [get_ports EPD_XCL]
set_property PACKAGE_PIN J20 [get_ports EPD_XLE]
set_property PACKAGE_PIN K18 [get_ports EPD_XSTL]
set_property PACKAGE_PIN J19 [get_ports {EPD_DOUT[15]}]
set_property PACKAGE_PIN G19 [get_ports {EPD_DOUT[14]}]
set_property PACKAGE_PIN H20 [get_ports {EPD_DOUT[13]}]
set_property PACKAGE_PIN G20 [get_ports {EPD_DOUT[12]}]
set_property PACKAGE_PIN J18 [get_ports {EPD_DOUT[11]}]
set_property PACKAGE_PIN K17 [get_ports {EPD_DOUT[10]}]
set_property PACKAGE_PIN F19 [get_ports {EPD_DOUT[9]}]
set_property PACKAGE_PIN E19 [get_ports {EPD_DOUT[8]}]
set_property PACKAGE_PIN F20 [get_ports {EPD_DOUT[7]}]
set_property PACKAGE_PIN D19 [get_ports {EPD_DOUT[6]}]
set_property PACKAGE_PIN H18 [get_ports {EPD_DOUT[5]}]
set_property PACKAGE_PIN D18 [get_ports {EPD_DOUT[4]}]
set_property PACKAGE_PIN D20 [get_ports {EPD_DOUT[3]}]
set_property PACKAGE_PIN H17 [get_ports {EPD_DOUT[2]}]
set_property PACKAGE_PIN C20 [get_ports {EPD_DOUT[1]}]
set_property PACKAGE_PIN B20 [get_ports {EPD_DOUT[0]}]

set_property PACKAGE_PIN P19 [get_ports pix_clk]
set_property PACKAGE_PIN R19 [get_ports de_i]
set_property PACKAGE_PIN P18 [get_ports hs_i]
set_property PACKAGE_PIN M17 [get_ports vs_i]
set_property PACKAGE_PIN V20 [get_ports {gray_i[7]}]
set_property PACKAGE_PIN U20 [get_ports {gray_i[6]}]
set_property PACKAGE_PIN U19 [get_ports {gray_i[5]}]
set_property PACKAGE_PIN T19 [get_ports {gray_i[4]}]
set_property PACKAGE_PIN T20 [get_ports {gray_i[3]}]
set_property PACKAGE_PIN P20 [get_ports {gray_i[2]}]
set_property PACKAGE_PIN R18 [get_ports {gray_i[1]}]
set_property PACKAGE_PIN N17 [get_ports {gray_i[0]}]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {pix_clk_IBUF}]

create_clock -period 20.000 -name clk [get_ports clk]
create_clock -period 10000.000 -name scl [get_ports scl]
create_clock -period 6.060 -name pix_clk [get_ports pix_clk]
create_clock -period 20 -name EPD_XCL [get_ports EPD_XCL]

set_input_delay -clock [get_clocks pix_clk] -rise -min 2.000 [get_ports {de_i hs_i {gray_i[0]} {gray_i[1]} {gray_i[2]} {gray_i[3]} {gray_i[4]} {gray_i[5]} {gray_i[6]} {gray_i[7]} vs_i}]

set_input_delay -clock [get_clocks pix_clk] -rise -max 4.700 [get_ports {de_i hs_i {gray_i[0]} {gray_i[1]} {gray_i[2]} {gray_i[3]} {gray_i[4]} {gray_i[5]} {gray_i[6]} {gray_i[7]} vs_i}]


set_false_path -from [get_ports rst_n] -to [all_registers]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]