// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of height
//        bit 15~0 - height[15:0] (Read/Write)
//        others   - reserved
// 0x14 : reserved
// 0x18 : Data signal of width
//        bit 15~0 - width[15:0] (Read/Write)
//        others   - reserved
// 0x1c : reserved
// 0x20 : Data signal of min
//        bit 7~0 - min[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// 0x28 : Data signal of max
//        bit 7~0 - max[7:0] (Read/Write)
//        others  - reserved
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XHLS_CONTRAST_STRETCH_AXILITES_ADDR_HEIGHT_DATA 0x10
#define XHLS_CONTRAST_STRETCH_AXILITES_BITS_HEIGHT_DATA 16
#define XHLS_CONTRAST_STRETCH_AXILITES_ADDR_WIDTH_DATA  0x18
#define XHLS_CONTRAST_STRETCH_AXILITES_BITS_WIDTH_DATA  16
#define XHLS_CONTRAST_STRETCH_AXILITES_ADDR_MIN_DATA    0x20
#define XHLS_CONTRAST_STRETCH_AXILITES_BITS_MIN_DATA    8
#define XHLS_CONTRAST_STRETCH_AXILITES_ADDR_MAX_DATA    0x28
#define XHLS_CONTRAST_STRETCH_AXILITES_BITS_MAX_DATA    8

