// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xhls_contrast_stretch.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHls_contrast_stretch_CfgInitialize(XHls_contrast_stretch *InstancePtr, XHls_contrast_stretch_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XHls_contrast_stretch_Set_height(XHls_contrast_stretch *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_contrast_stretch_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_HEIGHT_DATA, Data);
}

u32 XHls_contrast_stretch_Get_height(XHls_contrast_stretch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_contrast_stretch_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_HEIGHT_DATA);
    return Data;
}

void XHls_contrast_stretch_Set_width(XHls_contrast_stretch *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_contrast_stretch_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_WIDTH_DATA, Data);
}

u32 XHls_contrast_stretch_Get_width(XHls_contrast_stretch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_contrast_stretch_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_WIDTH_DATA);
    return Data;
}

void XHls_contrast_stretch_Set_min(XHls_contrast_stretch *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_contrast_stretch_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_MIN_DATA, Data);
}

u32 XHls_contrast_stretch_Get_min(XHls_contrast_stretch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_contrast_stretch_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_MIN_DATA);
    return Data;
}

void XHls_contrast_stretch_Set_max(XHls_contrast_stretch *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_contrast_stretch_WriteReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_MAX_DATA, Data);
}

u32 XHls_contrast_stretch_Get_max(XHls_contrast_stretch *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_contrast_stretch_ReadReg(InstancePtr->Axilites_BaseAddress, XHLS_CONTRAST_STRETCH_AXILITES_ADDR_MAX_DATA);
    return Data;
}

