// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhls_contrast_stretch.h"

extern XHls_contrast_stretch_Config XHls_contrast_stretch_ConfigTable[];

XHls_contrast_stretch_Config *XHls_contrast_stretch_LookupConfig(u16 DeviceId) {
	XHls_contrast_stretch_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHLS_CONTRAST_STRETCH_NUM_INSTANCES; Index++) {
		if (XHls_contrast_stretch_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHls_contrast_stretch_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHls_contrast_stretch_Initialize(XHls_contrast_stretch *InstancePtr, u16 DeviceId) {
	XHls_contrast_stretch_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHls_contrast_stretch_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHls_contrast_stretch_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

