######################################################################
#
# File name : display_mgr_tb.udo
# Created on: Fri Aug 19 19:39:24 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
