######################################################################
#
# File name : eink_controller_ed108_tb.udo
# Created on: Sat Oct 01 22:51:56 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
