######################################################################
#
# File name : frame_ctrl_tb_wave.do
# Created on: Wed Aug 31 20:20:30 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
