######################################################################
#
# File name : frame_ctrl_tb_elaborate.do
# Created on: Wed Aug 31 20:20:26 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.frame_ctrl_tb xil_defaultlib.glbl -o frame_ctrl_tb_opt

quit -force
