######################################################################
#
# File name : frame_ctrl_tb_simulate.do
# Created on: Wed Aug 31 20:20:30 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib frame_ctrl_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {frame_ctrl_tb_wave.do}

view wave
view structure
view signals

do {frame_ctrl_tb.udo}

run 0
