######################################################################
#
# File name : outRGB_tb.udo
# Created on: Sat Oct 01 17:58:09 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
