######################################################################
#
# File name : v_mirror_tb_elaborate.do
# Created on: Sun Sep 18 19:53:24 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_2020.1\\win64\\vopt +acc=npr -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.v_mirror_tb xil_defaultlib.glbl -o v_mirror_tb_opt

quit -force
